### ISSUE TITLE
作者你好

### ISSUE THREAD

**Issue by LoverFanFan** [sshiqiao/douyin-ios-objectc#10]
就是在滑动视频上下切换中，发现两个视频上下切换，视频并未从头播放而是处于暂停-播放-暂停-播放状态。请问这个问题应该如何解决？

**Comment by sshiqiao** [comment]
step1:修改AwemeListController observeValueForKeyPath方法中的[cell play] 改为 [cell replay]
<pre>
//判断当前cell的视频源是否已经准备播放
if(cell.isPlayerReady) {
     //播放视频
      [cell play]; 改为 [cell replay];
}
</pre>

step2:AVPlayerManager.m中的replay方法改为以下：
<pre>
- (void)replay:(AVPlayer *)player {
    [_playerArray enumerateObjectsUsingBlock:^(AVPlayer * obj, NSUInteger idx, BOOL *stop) {
        [obj pause];
    }];
    if([_playerArray containsObject:player]) {
        [player seekToTime:kCMTimeZero];
        [self play:player];
    }
}
</pre>
代码已上传，请查看。

**Comment by LoverFanFan** [comment]
多谢

**Comment by LoverFanFan** [comment]
多谢
