### ISSUE TITLE
demo很赞，但是确实有闪退的问题，具体原因如下。。。

### ISSUE THREAD

**Issue by ynnynn** [sshiqiao/douyin-ios-objectc#11]
Terminating app due to uncaught exception 'NSGenericException', reason: '*** Collection <__NSArrayM: 0x60c00005a9a0> was mutated while being enumerated.'

个人首页上下多次且快速的滚动就会出现（也不是很暴力的那种快速上下滑，都是些很普通的用户滚动操作）   ios11,8p

**Comment by sshiqiao** [comment]
好的，我看看。

**Comment by sshiqiao** [comment]
崩溃原因出现在WebPQueueManager中的requestQueueArray数组。当遍历数组时修改数组，导致出现以上问题。解决方法是在数组更新时加一个同步锁，确保不出现遍历数组的同时修改数组的情况。代码已上传，请查看。

**Comment by ynnynn** [comment]
感谢作者付出！

**Comment by sshiqiao** [comment]
代码已更新，请查看。

**Comment by ynnynn** [comment]
感谢！
