### ISSUE TITLE
一个小问题

### ISSUE THREAD

**Issue by CoderST** [sshiqiao/douyin-ios-objectc#12]
你好大神,在视频详情页 跑马灯滚动动画里  如果文字带有emoji 高度会有偏差, 滚动的动画和前面的音乐符号就不对齐了
   谢谢.

**Comment by sshiqiao** [comment]
说明：跑马灯循环滚动文字控件由自定义UIView内添加CATextLayer文字层实现，CATextLayer文字层应该垂直居中于UIView。

修改步骤如下：

step1:在CircleTextView控件的layoutSubviews方法中修改的CATextLayer位置，使CATextLayer文字层垂直居中于UIView；
<pre>
_textLayer.frame = CGRectMake(0, self.bounds.size.height/2 - _textLayerFrame.size.height/2, _textLayerFrame.size.width, _textLayerFrame.size.height);
</pre>

step2:修改AwemeListCell中CircleTextView控件对象musicName高度，之前设置了20而实际文字高度为24，导致不对齐的问题；
<pre>
[_musicName mas_makeConstraints:^(MASConstraintMaker *make) {
        make.left.equalTo(self.musicIcon.mas_right);
        make.centerY.equalTo(self.musicIcon);
        make.width.mas_equalTo(SCREEN_WIDTH/2);
       //高度20改为24
        make.height.mas_equalTo(24);
}];
</pre>
代码已上传，请查看。
