### ISSUE TITLE
请教一个问题

### ISSUE THREAD

**Issue by CoderST** [sshiqiao/douyin-ios-objectc#13]
您好大神,我看抖音的视频滚动的时候,在下一个cell(不知道是不是cell)还未出现的时候,基本数据已经加载完毕了, 目前demo情况是 如果网络情况不稳定的时候,在滚动下一个cell  会出现视频头图没有加载出来,要等待此时的数据赋值给cell进行数据的加载,  想请教一下,不知道用tableview,能否实现抖音的这种效果.
谢谢~~

**Comment by sshiqiao** [comment]
在UITableView范围内的cell才会调用cellForRowAtIndexPath等代理方法进行cell数据填充，扩大UITableView的范围并同时调整UITableView的contentInset值即可实现抖音这种预先加载未出现cell的效果，代码修改如下：
<pre>
//设置UITableView的Frame为单个cell的5倍高
_tableView = [[UITableView alloc] initWithFrame:CGRectMake(0, 0, SCREEN_WIDTH, SCREEN_HEIGHT * 5)];
//设置UITableView内容显示区域为单个cell高
_tableView.contentInset = UIEdgeInsetsMake(0, 0, SCREEN_HEIGHT * 4, 0);
//以上即可出现每次滑动会预先加载后面四个未显示cell的效果
</pre>

代码已上传，请查看。（顺便[这里](https://stackoverflow.com/questions/21053874/number-of-visible-cells-in-uitableview)有不限于UITableView的解决方案）
