### ISSUE TITLE
demo首页上下切换视频会报错？

### ISSUE THREAD

**Issue by kafka000** [sshiqiao/douyin-ios-objectc#14]
首先赞许下app，其次问题如题，报错信息如下：
objc[5943]: Class VCWeakObjectHolder is implemented in both /Applications/Xcode9.4.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/Library/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/AVConference.framework/Frameworks/ViceroyTrace.framework/ViceroyTrace (0x1267234d0) and /Applications/Xcode9.4.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/Library/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/AVConference.framework/AVConference (0x12584fe38). One of the two will be used. Which one is undefined.

**Comment by sshiqiao** [comment]
> 首先赞许下app，其次问题如题，报错信息如下：
> objc[5943]: Class VCWeakObjectHolder is implemented in both /Applications/Xcode9.4.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/Library/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/AVConference.framework/Frameworks/ViceroyTrace.framework/ViceroyTrace (0x1267234d0) and /Applications/Xcode9.4.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/Library/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/AVConference.framework/AVConference (0x12584fe38). One of the two will be used. Which one is undefined.

你好，demo目前未遇到这种情况，不过你可以点击[这里](https://stackoverflow.com/questions/49994063/error-class-vcweakobjectholder-is-implemented-in-both-is-crashing-debug-ses)尝试解决上诉问题。

**Comment by kafka000** [comment]
> > 首先赞许下app，其次问题如题，报错信息如下：
> > objc[5943]: Class VCWeakObjectHolder is implemented in both /Applications/Xcode9.4.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/Library/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/AVConference.framework/Frameworks/ViceroyTrace.framework/ViceroyTrace (0x1267234d0) and /Applications/Xcode9.4.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/Library/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/AVConference.framework/AVConference (0x12584fe38). One of the two will be used. Which one is undefined.
> 
> 你好，demo目前未遇到这种情况，不过你可以点击[这里](https://stackoverflow.com/questions/49994063/error-class-vcweakobjectholder-is-implemented-in-both-is-crashing-debug-ses)尝试解决上诉问题。

     解决了 谢谢！
