### ISSUE TITLE
视频加载失败问题

### ISSUE THREAD

**Issue by DolphinQuan** [sshiqiao/douyin-ios-objectc#17]
你好，大神。我在改动网络数据来源从本地json，并且在favorites.json数据下把列表数据重复增加到150多个情况下，多次在UserHomePageController的顶部和底部之间滑动，并且随机点一个collectioncell 进入AwemeListController后，再返回到UserHomePageController，就会出现AVPlayerItemStatusFailed，加载失败了，没法播放。请问这个问题要如何解决？感谢！

**Comment by sshiqiao** [comment]
你好，看了一下基本是request time out的问题。
在AVPlayerView类添加了一个retry的方法，尝试重新加载视频，代码已经提交，你可以看看。
然后，AVPlayerItem中有个error方法可以用于判断具体是出现了什么问题，你可以尝试打印这个error具体查看问题所在。

**Comment by DolphinQuan** [comment]
还是会复现，下面是AVPlayerItem的error log，还有其他log信息。好像缓存那边有问题。
##############
2018-11-28 14:22:17.185595+0800 Douyin[2187:628150] Error Domain=AVFoundationErrorDomain Code=-11839 "Cannot Decode" UserInfo={NSLocalizedDescription=Cannot Decode, NSUnderlyingError=0x283a27300 {Error Domain=NSOSStatusErrorDomain Code=-12913 "(null)"}, NSLocalizedRecoverySuggestion=Stop any other actions that decode media and try again., NSLocalizedFailureReason=The decoder required for this media is busy.}
2018-11-28 14:22:17.185609+0800 Douyin[2187:628150] 
##############
Task <F033E181-0ADA-4EC5-9B55-288ACD1D7EC4>.<1> load failed with error Error Domain=NSURLErrorDomain Code=-1004 "Could not connect to the server." UserInfo={_kCFStreamErrorCodeKey=61, NSUnderlyingError=0x283a249c0 {Error Domain=kCFErrorDomainCFNetwork Code=-1004 "(null)" UserInfo={_kCFStreamErrorCodeKey=61, _kCFStreamErrorDomainKey=1}}, _NSURLErrorFailingURLSessionTaskErrorKey=LocalDataTask <F033E181-0ADA-4EC5-9B55-288ACD1D7EC4>.<1>, _NSURLErrorRelatedURLSessionTaskErrorKey=(
    "LocalDataTask <F033E181-0ADA-4EC5-9B55-288ACD1D7EC4>.<1>"
), NSLocalizedDescription=Could not connect to the server., NSErrorFailingURLStringKey=https://localhost/var/mobile/Containers/Data/Application/0069C9CC-01DA-48E6-A664-660FA1D9BE2F/Documents/webCache/7748215b87b0c34f38557305cd290e54.mp4, NSErrorFailingURLKey=https://localhost/var/mobile/Containers/Data/Application/0069C9CC-01DA-48E6-A664-660FA1D9BE2F/Documents/webCache/7748215b87b0c34f38557305cd290e54.mp4, _kCFStreamErrorDomainKey=1} [-1004]

**Comment by mercyxu** [comment]
你好,我这里同样的问题,替换自己的数据源,正常滑动,很多视频无法加载,加载超时AVPlayerItemStatusFailed

**Comment by sshiqiao** [comment]
@DolphinQuan 
有空会重构一下视频播放这块，没花太多时间写的demo，有许多设计的不太好的地方。

@mercyxu 
demo播放的是抖音平台上的视频源，都是moov在前的mp4格式，其他格式没有进行过具体适配。

**Comment by DolphinQuan** [comment]
感谢大大的维护 Orz

**Comment by chengzj456** [comment]
这个问题解决了吗？现在用最新版本还是经常出现加载失败

**Comment by millascott** [comment]
在avplayerItem的状态报failed的时候重新setPlayerSourceUrl好像能解决问题，要处理下不要死循环。
