### ISSUE TITLE
是不是接口不能用了？运行起来后视频都播放不了了

### ISSUE THREAD

**Issue by yangzheng006** [sshiqiao/douyin-ios-objectc#2]

**Comment by sshiqiao** [comment]
你好，视频播放资源在抖音服务器上，仿抖音demo只是将资源地址存储在了个人服务器数据库中，个人服务器无法正常响应的情况下会调用本地数据。理论上讲，在网络良好的情况下不会出现无法加载的现象，建议试试关闭VPN或者使用真机进行测试。最新代码修复了iOS8、iOS9、iOS10上出现的bug，可以拉取看看是否还有相关问题。

**Comment by zhao1zhihui** [comment]
个人服务器使用是么写的  抓取的json数据怎么写进个人服务器

**Comment by sshiqiao** [comment]
java写的服务器，数据库根据json数据建表，通过代码读取json数据并保存至数据库相应表中。
