### ISSUE TITLE
添加了上拉加载功能后刷新table，视频会定住

### ISSUE THREAD

**Issue by chengzongxin** [sshiqiao/douyin-ios-objectc#20]
大神你好,这是个非常赞的一个仿抖音项目,我也集成在自己的项目里了,但是我在视频上下滑动里面添加了一个上拉加载更多视频的功能(用的也是源码中LoadMoreController实现的),加载完数据,刷新tableview,出现了一个问题

简单来说就是,添加了上拉加载用接口请求更多视频后刷新table，当前视频会定住.

具体步骤是:
1.上拉后,会把下一个cell滑动到当前屏幕位置,然后正在播放cell中视频,与此同时loadMore(LoadMoreController 实例对象)也会加载下一页数据

2.当loadMore数据接口返回后,会更新到数据源data中.之后刷新tableview

3.当调用【tableview reloaddata】后,当前正在播放的cell画面会停住,当前屏幕会定住,但背景音乐还是在播放,点击屏幕后,视频又会从最开始播放(不是接着之前的播放进度,应该是点击播放后[AVPlayerManager]暂停了在后台运行的player,然后播放了当前cell的player,感觉这里体验很不好)

很严重的一个bug，不知道怎么解决，不知道可有其他解决方案？

PS:发现一个类似的案例:https://www.jianshu.com/p/7b47e63bf593

**Comment by sshiqiao** [comment]
你好，这个的确是bug额...
demo中“作品”类别使用的局部刷新，“喜欢列表”使用的是reloaddata，应该统一使用局部刷新。
修改如下：
[wself.data addObjectsFromArray:array];
[wself.tableView reloadData]；

改为

[wself.tableView beginUpdates];
[wself.data addObjectsFromArray:array];
NSMutableArray<NSIndexPath *> *indexPaths = [NSMutableArray array];
for(NSInteger row = wself.data.count - array.count; row<wself.data.count; row++) {
      NSIndexPath *indexPath = [NSIndexPath indexPathForRow:row inSection:0];
      [indexPaths addObject:indexPath];
}
[wself.tableView insertRowsAtIndexPaths:indexPaths withRowAnimation:NO];
[wself.tableView endUpdates];

代码已上传，请查看。

**Comment by chengzongxin** [comment]
@sshiqiao 谢谢回复

我没看到你新上传的代码,把你说的局部刷新方法替换reloaddata,问题还是没有解决哦

貌似,局部刷新和直接reloaddata,都会释放当前cell,然后再重新加载cell,即使把动画改成NO也是一样的

所以这个问题我试过很多办法都没办法修复

复现步骤:

AwemeListController中,上滑加载更多视频的时候,只有请求,没有更新数据源,所以也不会刷新table,只要请求了接口刷新tableview,bug就会复现了,即使换成局部刷新也还是不行,你可以试试哈

**Comment by sshiqiao** [comment]
不会的，你再试试看，代码上传了。

**Comment by chengzongxin** [comment]
换成局部刷新还是不行的哦


- (void)loadData:(NSInteger)pageIndex pageSize:(NSInteger)pageSize {
    
    // 2秒模拟网络延迟
    dispatch_after(dispatch_time(DISPATCH_TIME_NOW, (int64_t)(2 * NSEC_PER_SEC)), dispatch_get_main_queue(), ^{
        NSArray *array = [NSArray arrayWithArray:self.data];
        
        [self.tableView beginUpdates];
        [self.data addObjectsFromArray:array];
        NSMutableArray<NSIndexPath *> *indexPaths = [NSMutableArray array];
        for(NSInteger row = self.data.count - array.count; row<self.data.count; row++) {
            NSIndexPath *indexPath = [NSIndexPath indexPathForRow:row inSection:0];
            [indexPaths addObject:indexPath];
        }
        [self.tableView insertRowsAtIndexPaths:indexPaths withRowAnimation:NO];
        [self.tableView endUpdates];
        
        [self.loadMore endLoading];
    });
}


你把这段代码替换上去,就能看到bug了

**Comment by chengzongxin** [comment]
@sshiqiao 此外还想提一点建议哈

因为我看到你是用AVPlayerManager单例管理所有的player的播放,暂停,重放等

如果有滑动功能的haul,越到后面滑动的越多,单例里面的player就会越来越多,每次播放器播放,暂停什么的,都会遍历所有player,对性能有不必要的开销

如果能在适当的时机,删除playerarray里面的播放器那就很好了

**Comment by w819314930** [comment]
如何实现下拉加载功能。。大佬

**Comment by chengzongxin** [comment]
> 如何实现下拉加载功能。。大佬



> 如何实现下拉加载功能。。大佬

**Comment by chengzongxin** [comment]
> 如何实现下拉加载功能。。大佬

加个MJRefresh不就可以了
