### ISSUE TITLE
MP4视频的头信息在尾部的时候，视频边下边播用不了，您有什么好的解决方法吗？

### ISSUE THREAD

**Issue by qingwu126** [sshiqiao/douyin-ios-objectc#3]

**Comment by qingwu126** [comment]
http://fxactvideodev.fenxuekeji.com/76917/video/development_d165bd58-8dd0-4b39-a40f-a46f2077b7ea.mp4
例如这个视频

**Comment by qingwu126** [comment]
目前这个视频加载就播放不了

**Comment by sshiqiao** [comment]
你说的是MP4格式的moov数据在视频最后的情况吧，要么让项目中的MP4格式统一moov在前面，要么就先通过Range参数先读取网络视频末尾的moov再从头读取视频数据，我有空写个demo吧～
