### ISSUE TITLE
Xcode11运行播放视频黑屏是怎么回事？

### ISSUE THREAD

**Issue by qingwu126** [sshiqiao/douyin-ios-objectc#37]
Xcode11运行播放视频黑屏是怎么回事？iOS12.4.2运行

**Comment by qingwu126** [comment]
播放只有声音没有画面

**Comment by qingwu126** [comment]
视频转换为h265格式，但是AVPlayer不支持h265，所以播放黑屏

**Comment by isdotjim** [comment]
搭个车...
想邀请Repo作者来w3c.group创建项目的对应小组。w3c.group是类似知识星球的社群工具，小组可设置为付费且有赞助功能，同时也是一个区块链主导的创作者社区。这是相关介绍：
http://t.cn/Ai1vLcCU
http://t.cn/Ai1vLcCG
http://t.cn/Ai1vLcCA
